name: detection_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alabaster=0.7.16
  - arrow=1.2.3
  - astroid=2.11.7
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.6.0
  - blas=1.1
  - bleach=4.1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - comm=0.1.2
  - cookiecutter=1.7.3
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2022.2.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - docutils=0.21.2
  - eigen=3.4.0
  - entrypoints=0.4
  - expat=2.4.9
  - ffmpeg=4.2.2
  - flake8=4.0.1
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fsspec=2024.3.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.33.1
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.1
  - jeepney=0.7.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyterlab_pygments=0.1.2
  - jxrlib=1.1
  - keyring=23.4.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.88.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mypy_extensions=0.4.3
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpydoc=1.5.0
  - openblas=0.3.20
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.10.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - poyo=0.5.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - py-cpuinfo=9.0.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=2.4.0
  - pygments=2.18.0
  - pylint=2.14.5
  - pyls-spyder=0.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.5.0
  - python-slugify=5.0.2
  - python_abi=3.10
  - pytz=2022.7
  - pywavelets=1.5.0
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - rope=0.22.0
  - rtree=1.0.1
  - scikit-image=0.20.0
  - scipy=1.8.1
  - seaborn=0.12.2
  - secretstorage=3.3.1
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.10
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.3.3
  - spyder-kernels=2.3.3
  - sqlite=3.40.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.66.1
  - traitlets=5.7.1
  - tzdata=2022a
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.14
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.43.0
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - x264=1!157.20191217
  - xz=5.2.10
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - arabic-reshaper==3.0.0
      - asn1crypto==1.5.1
      - einops==0.3.2
      - et-xmlfile==2.0.0
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - json-tricks==3.16.1
      - mpmath==1.2.1
      - networkx==3.3
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - protobuf==3.20.3
      - pydeprecate==0.3.2
      - pypdf==4.2.0
      - pypng==0.20220715.0
      - pyproject-hooks==1.1.0
      - pyqt5-sip==12.11.0
      - python-bidi==0.4.2
      - qrcode==7.4.2
      - rapidfuzz==3.9.0
      - stringcase==1.2.0
      - sympy==1.13.1
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - torch==2.5.1
      - torchvision==0.20.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzlocal==5.2
      - ultralytics==8.3.98
      - ultralytics-thop==2.0.14
      - uritools==4.0.2
      - werkzeug==3.0.3